const letrasAlfabeto = [
  { letra: 'A', palavra: 'Abelha' },
  { letra: 'B', palavra: 'Bola' },
  { letra: 'C', palavra: 'Casa' },
  { letra: 'D', palavra: 'Dado' },
  { letra: 'E', palavra: 'Elefante' },
  { letra: 'F', palavra: 'Foca' },
  { letra: 'G', palavra: 'Gato' },
  { letra: 'H', palavra: 'Helicóptero' },
  { letra: 'I', palavra: 'Igreja' },
  { letra: 'J', palavra: 'Jacaré' },
  { letra: 'K', palavra: 'Kiwi' },
  { letra: 'L', palavra: 'Lápis' },
  { letra: 'M', palavra: 'Macaco' },
  { letra: 'N', palavra: 'Navio' },
  { letra: 'O', palavra: 'Ovo' },
  { letra: 'P', palavra: 'Pato' },
  { letra: 'Q', palavra: 'Queijo' },
  { letra: 'R', palavra: 'Rato' },
  { letra: 'S', palavra: 'Sapo' },
  { letra: 'T', palavra: 'Tigre' },
  { letra: 'U', palavra: 'Urso' },
  { letra: 'V', palavra: 'Vaca' },
  { letra: 'W', palavra: 'Waffle' },
  { letra: 'X', palavra: 'Xícara' },
  { letra: 'Y', palavra: 'Yakult' },
  { letra: 'Z', palavra: 'Zebra' }
];
